### PR TITLE
populate newsletters

### PR DESCRIPTION
**Pull request by jacobayu**
### Administrative Info
Monday Board ID: 1181608900
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Populated the Sakyadhita Newsletter pages with links to all of the existing newsletters that are on SI's original website, used dummy images for all of them for now.

### Testing
How did you confirm your changes worked? 
- Manually viewed the pages, as well as double checked to make sure all newsletters are accounted for, clicked on several links to make sure they took user to the actual pdf

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

First Page of SI Newsletters
Screen Shot 2021-11-19 at 5 12 07 PM

Third Page of SI Newsletters showing the navigation bar
Screen Shot 2021-11-19 at 5 12 19 PM

### CODE REVIEW

**Review by aaron-kirk — CHANGES_REQUESTED** [review]
Clicked through every link -- looks like they all take you to the right volume/number.

You are missing Vol 13, Number 2 from 2003 (https://sakyadhita.org/docs/resources/newsletters/13-2-2003.pdf).

That one aside, the counts match up (excluding the missing links for volumes 17 and 1).

**Comment by jacobayu** [comment]
> Clicked through every link -- looks like they all take you to the right volume/number.
> 
> You are missing Vol 13, Number 2 from 2003 (https://sakyadhita.org/docs/resources/newsletters/13-2-2003.pdf).
> 
> That one aside, the counts match up (excluding the missing links for volumes 17 and 1).

dang good catch, I just added the news letter and the images for the newsletters that had them

**Review by aaron-kirk — APPROVED** [review]
Counts seem to match up now. LPTM (looks poggers to me)!

**Review by Amrit-S — APPROVED** [review]
Great job. Please update your branch with main so we can merge :)

**Pull request merged**
