### PR TITLE
Feature/aaron kirk/1898570607 populate about us

### PR DESCRIPTION
**Pull request by aaron-kirk**
### Administrative Info
Monday Board ID: 1181608900
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Filled out `seeds/models/execCommittee.js` based on https://sakyadhita.org/home/exec.html

### Testing
How did you confirm your changes worked? 
- Compared current website to my changes

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

image

### CODE REVIEW

**Comment by aaron-kirk** [comment]
The "Branch & Chapter Coordinator" title looks a bit scuffed because it's so long it takes up 3 lines. Not sure what to change >_>

**Review by Amrit-S — CHANGES_REQUESTED** [review]
You're missing the 2021-2025 exec committee.

Also don't forget to add in the Founding Member profiles too.

**Review by amiteshksharma — COMMENTED** [review]
Update your redirect/other links inside the seeds/models to use dropbox and I'll approve. Lmk if you don't need to use dropbox on Slack and I'll approve it then

**Review by Amrit-S — APPROVED** [review]
Amazing! :)

**Review by jacobayu — APPROVED** [review]
ldtm (looks daebak to me)

**Pull request merged**
