### PR TITLE
Reusable resources header component

### PR DESCRIPTION
**Pull request by dnanjunda**
### Administrative Info
Monday Board ID: 1181608900
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Made a component for the resources header

### Testing
How did you confirm your changes worked? 
- Load the join page on desktop and mobile screen sizes

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

Desktop:
Desktop_Header

Mobile:
Mobile_Header

### CODE REVIEW

**Review by PatrickBrown1 — APPROVED** [review]
Looks good to me! The only comment is that we should probably cap the header at 100vh, just so it doesn't go on forever at mobile views.

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Hey Dhanush - nice job!
So my big thing for this one is that all of the props are to some degree required, when that shouldn't be the case.
Case in point: No title
Screen Shot 2021-05-18 at 10 27 20 PM

Case in point: No text
Screen Shot 2021-05-18 at 10 27 57 PM

There is empty space if I don't pass these, and I don't want that to occur. If there is no text passed, then only title should be shown and its purple background adjusted to fit the title's height and width (with maybe some additional room for padding). There shouldn't be a blockade of empty space. Same thing for text as well.
Also, I'd like you to have a width and height prop for how big you want the component to big. This will be useful since we'd use this prop for the Resources Landing page, which takes up the entire screen.

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Issue with resizing on the purple div. Its getting stretched too small. I think you did the width and height of the div itself to be in terms of "vw" or "vh" until perhaps mobile view. Don't do that. Just have the width be in terms of a standard number of pixels instead (i.e., 350 pixels) and have the height be "fit-content", so you don't get this problem. You might have to reduce the width size at strategic width sizes so it doesn't overflow the screen. 

Screen Shot 2021-05-23 at 6 14 47 PM

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Temp comment...

**Review by Amrit-S — APPROVED** [review]
Alright, Dhanush nice job! 

I'm approving this PR because we have a lot of other pages that need this, so any remaining bugs on this will have to be taken care of later. 

Case in point (Safari):

Guess fit-height doesn't play well with Safari. A similar problem is happening with home page on this, so the solution to this problem should be the same for both. We'll address this in a future PR. 

Screen Shot 2021-05-24 at 12 36 45 AM

**Pull request merged**
