### PR TITLE
News and Events schema

### PR DESCRIPTION
**Pull request by alexrodpas**
### Administrative Info
Monday Board ID: 1293189884

### Changes
What changes did you make?
- Implemented schema for News and Events
    - /db/models/newsAndEvents.js
    - /db/services/newsAndEvents.js
    - /routes/newsAndEvents.js
    - /seeds/newsAndEvents.js
    - & adding lines to config and initializeTables to make sure they were used

### Testing
How did you confirm your changes worked? 
- Lint check found no errors.
- Unfortunately I can't get MySQL to work for some reason so I couldn't do much testing but I think the script populating the tables should run without issue.
- Please do some testing for me and I'll make the necessary changes.

### CODE REVIEW

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Alright so nice job!

I fixed some of the issues I saw regarding seeding and a response issue I noticed with delete.

I tested it and it seems to be working.

Only thing is I'd suggest you modify your DELETE route to handle the case where the DELETE is unsuccessful for any reason.

**Review by thomas-gg — APPROVED** [review]
lgtm

**Comment by thomas-gg** [comment]
**** sorry i approved to early, there is an issue with the delete in that it says delete unsuccessful when it is successful

**Review by thomas-gg — APPROVED** [review]

**Review by Amrit-S — APPROVED** [review]
lgtm

**Pull request merged**
