### PR TITLE
Feature/patrick brown1/1737708872 sync backend newsletters

### PR DESCRIPTION
**Pull request by PatrickBrown1**
### Administrative Info
Monday Board ID: 1181608900
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Hooked up newsletters with backend route

### Testing
How did you confirm your changes worked? 
- Go to newsletters, should render based on backend route results
### Confirmation of Change 
image

### CODE REVIEW

**Comment by PatrickBrown1** [comment]
image
Updated with volume and number

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Looks bomb Patrick (as usual)!!

Make sure to create a component for a spinner from Material UI, and integrate that to show while data is being fetched. Other that lgtm for me ~

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Very small thing. I sent you a slack for more details, but in your FETCH request you are assuming you are always getting a response code 200. 

That's not technically true. You need to account for cases where the backend call fails and sends you something else, like a 500. I suggest first checking the status code and passing yourself an empty array if its a 500 so your code doesn't crash. 
Screen Shot 2021-10-08 at 2 00 11 AM

**Review by Amrit-S — COMMENTED** [review]
LGTM! Just waiting on Amitesh's approval first :)

**Review by ASharma2001 — APPROVED** [review]
lgtm Patrick. Thanks for the spinner and the utils file, and Good luck with your new role as DM

**Review by amiteshksharma — APPROVED** [review]
approved with the wrong account

**Review by Amrit-S — APPROVED** [review]
lgtm

**Pull request merged**
