### PR TITLE
Backend Sync for Join Us and Volunteer Pages

### PR DESCRIPTION
**Pull request by dnanjunda**
### Administrative Info
Monday Board ID: 1181608900
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Synced join us and volunteer pages with backend
- Connected functionality with paypal component
- Added a modal for Paypal buttons
- Will add comments

### Testing
How did you confirm your changes worked? 
- Tested filling out and submitting all the forms (Volunteer, Email list only sign up, and membership)
- Tried submitting various payments through paypal (donation, no donation, etc.)

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

Volunteer Page Form:
https://user-images.githubusercontent.com/57281768/137445683-5555ddb9-ad73-4fd0-944b-ab49cd97cb29.mov

Join Us Page Form (Membership):
https://user-images.githubusercontent.com/57281768/137445720-34757f7e-3055-46a5-b75e-395acadf73d4.mov

### CODE REVIEW

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Okay nice Job Dhanush.

1. Your buttons on JoinUs (and the pop-up for payment) are too rounded. They're aesthetic should be similar to the ones we have on the other pages. See the Conferences page for reference. 
Screen Shot 2021-10-16 at 7 21 05 PM

2. For Join Us & Volunteer, form submission should trigger this modal:
Screen Shot 2021-10-16 at 7 13 27 PM
 
Think Amitesh already made a component for this so you can just reuse his.

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Okay Dhanush, better. 

I went back to your PR and made some changes to the buttons so that issue is solved and fixed a bug or two on your end. Sorry this PR is taking a bit longer to do. 

Some things:
1. Can you actually make the phone field optional for all the pages? I've already updated the backend so this change is reflected.
2. That PayPal freeze issue I slacked you about. 
3. And on the mobile layout options, your submit/return to form buttons look quite off center. Your PayPal modal is also more on the bottom of the screen, not in the middle.
Screen Shot 2021-10-21 at 9 51 21 PM
Screen Shot 2021-10-21 at 9 51 28 PM

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Alright, we're close to the finish line on this PR. 

Only thing i noticed was that you aren't checking if at least interest is checked on the Volunteer page before submitting the backend request. When I submit without checking interests, I get the following message and as a 
user I'd be super confused: 
Screen Shot 2021-11-01 at 9 01 17 PM



Other than that, I need to attach the PayPal IPN to this PR and do some quick email templates, but that's on me :) 

I appreciate your patience really

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Can you add some red text stating "At least one committee must be selected." as the error message that appears under the "Select all committees you are interested in." text for volunteer committees in the form?

**Review by amiteshksharma — APPROVED** [review]
LGTM. Addressed issues with amrit already

**Pull request merged**
