### PR TITLE
Feature/thomas gg/1318937787 backend accounts

### PR DESCRIPTION
**Pull request by thomas-gg**
### Administrative Info
Monday Board ID: 1181608900
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Added Register, Login, and Modify Password functionality for the admin account users.

### Testing
How did you confirm your changes worked? 
- Post requests on adminAccounts/register - duplicate user email and invalid user info.
- Put requests on adminAccounts/changePassword 
- Post requests on adminAccounts/login

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.
Post adminAccounts/register
```
{
    "name": "Sakyadhita",
    "email": "sakyadhita@gmail.com",
    "password": "LdrsaJ@QxgvM",
    "secret": "<INSERT_LOCAL_SECRET_HERE>"
}
```
Put adminAccounts/changePassword
```
{
    "email": "sakyadhita@gmail.com",
    "oldPassword": "LdrsaJ@QxgvM",
    "newPassword": "cats@rec00l"
}
```
Post adminAccounts/login
```
{
    "email": "sakyadhita@gmail.com",
    "password": "cats@rec00l"
}
```

### CODE REVIEW

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Nice job Thomas! You had a few logic flow issues but I just went back and fixed those myself.

Few things:

1. Can you go back and add @body tags to all your route headers? Right now only one has it, and the commenting style is very inconsistent.
2. This is also regarding inconsistency with any additional errors being reported. I underlined in red three different forms of sending an error. Choose one and stick with that. 
Screen Shot 2021-06-02 at 1 30 16 PM
Screen Shot 2021-06-02 at 1 30 23 PM

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Alright, looks good. Added OAuth2 for email automation + seeding. 

Just waiting for you to update the branch :)

**Review by Amrit-S — APPROVED** [review]
lgtm

**Review by PatrickBrown1 — APPROVED** [review]
this looks amazing good work

**Pull request merged**
