### PR TITLE
Feature/thomas gg/1254071572 conferences

### PR DESCRIPTION
**Pull request by thomas-gg**
### Administrative Info
Monday Board ID: 1181608900

### Changes
What changes did you make?
- Added Conferences routes for get, create, edit
- Added body requirements

### Testing
How did you confirm your changes worked? 
- tested expected valid and invalid input
- possibly found an issue with the edit functionality --> can't require slideShowImages and the other arrays to conform correctly

### Confirmation of Change 
To test functionality perform post, get and put requests in that order.
1. post request on http://localhost:3000/conference/addConference
```
{
    "title": "Cat ",
    "confNum": 1,
    "location": "San Diego",
    "slideShowImages": {
        "urls": ["cat", "dog"]
    },
    "programs": {
        "data":[{
            "description":"Emminent Buddhist Women",
            "url": "eminentbuddhists.com"
        }]
    },
    "presentations": {
        "data":[{
            "description":"presentations",
            "url": "eminentbuddhists.com"
        }]
    },
    "abstracts": {
        "data": [
            {
                "description": "abstracts",
                "url": "eminentbuddhists.com"
            }
        ]
    },
    "video": "google.com",
    "theme": "Lorem Ipsum Dolor"
}
```
2. get request --> http://localhost:3000/conference/getAllConferences
3. put request --> http://localhost:3000/conference/editConference/1
```
{
    "title": "different title!",
    "location": "sc"
}
```
This is a subset of the conferences, but of course this needs include certain items when testing.

~~I am aware there is an issue with the put request and arrays, will solve soon.~~ *resolved

### CODE REVIEW

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Discussed over Slack call: 

Update routes so all array like fields are required, in order to make edits easier to do with few assumptions. Those attributes must have custom validation done in the route itself to check that the JSON structure contains "description" and "url" tags for it. It will not be taken care of by the schema declaration since sequelize does not have such extensive JSON support.  All other fields that are optional should be optional, and optional fields can have NULL values in the table.

**Review by dnanjunda — APPROVED** [review]
LGTM! Great job.

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Few minor things.

Keep your routes consistent, and have try-catch blocks around all of them, not just some. Make sure to return a 500 error if by chance there ends up being any error in your route - that's only there for edit, but add it in for the rest to be safe. You have an extra space in your signupLink in your body parser, and for seeding, you have named your table "Sample" instead of Conferences. Also, make sure that _id, createdAt, and modifiedAt are not editable by any of your calls. 

Lastly, forgot to put this in the docs, but have the get request on conferences return by descending conference numbers (first one is latest, last one is earliest).

**Review by Amrit-S — APPROVED** [review]
Congrats on getting your first PR merged in Thomas!

**Pull request merged**
