### PR TITLE
Feature/aaron kirk/1277905903 about us

### PR DESCRIPTION
**Pull request by aaron-kirk**
### Administrative Info
Monday Board ID: 1181608900
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Added content for the mission, history, committee, founders section
- Added sticky nav that updates underline on scroll
- Committees can change content based on year through a dropdown menu
- Mobile view

### Testing
How did you confirm your changes worked? 
- Tested every mobile view on Chrome Devtools

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.
https://youtu.be/MwvWmS8HfRk

### CODE REVIEW

**Review by amiteshksharma — CHANGES_REQUESTED** [review]
Great PR, the page looks great but I have a couple of comments here. 

1) For the mobile/tablet view I think the banner on the photo at the top seems small for about 500px - 700px. I don't know if this is a you problem since I believe this was a separate PR? but I think it looks very small for those larger mobile/tablet screens 

image

2) The font could be a little bigger for the executive members details (mostly just the paragraph about them)

image

3) The photo at the bottom seems to be smaller than the other two photos on the page for mobile screen and I think we should try to keep the size consistent. 

image

image

**Comment by aaron-kirk** [comment]
Addressed the first two suggestions. 

Regarding the last one, I had initially made the last size the same way as the other images, but decided against it because the text on the banner in the image would be cut off. Because this image is definite rather than filler and is directly related to the section (the founding of Sakyadhita) I thought it was important enough to keep the sizing original to at least show the whole text (and maybe, less importantly, not cut off the people).

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Fabulous job Aaron!

Before we start with the comments, I would like to draw attention that you looked so freaking adorable as a kid. So much sass:
Screen Shot 2021-05-28 at 1 52 56 AM

Okay, now moving on to the comments.

Few things:

1. On desktop, your scroll thing on the left slides into the footer:
Screen Shot 2021-05-28 at 1 42 56 AM

2. In Pixel2XL landscape layout, for some reason your layout of 4 execs is 1 on top and 3 on bottom? Uh why? Is there a reason 2:2 wasn't working?
Screen Shot 2021-05-28 at 1 48 51 AM

3. For mobile, amount of white-space between each of the execs is just a _bit_ too much in my opinion. I would reduce it slightly. 
Screen Shot 2021-05-28 at 1 51 58 AM

4. None of the execs have links attached? It's in the design so gotta include it.

**Review by Amrit-S — COMMENTED** [review]
Looks amazing Aaron! Just waiting for Amitesh's approval otherwise I think its good to go.

Merge your branch with main please.

**Review by amiteshksharma — APPROVED** [review]
LGTM! good work

**Review by Amrit-S — APPROVED** [review]
LGTM! Looks bomb

**Pull request merged**
