### PR TITLE
Executive Committee synced with backend

### PR DESCRIPTION
**Pull request by aaron-kirk**
### Administrative Info
Monday Board ID: 1181608900
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Updated Executive Committee section of About page to pull profiles from backend

### Testing
How did you confirm your changes worked? 
- Used some dummy data

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

https://user-images.githubusercontent.com/36803028/139557085-036ad1df-711b-4b69-ad86-85d5500e8d18.mp4

### CODE REVIEW

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Alright, nice job Aaron. Not much to critique :) 

So few things:

1. I think you have all your backend calls in your _AboutUs.js_ file directly. You really should have them in the _util/requests.js_ file, and just import that file into _AboutUs.js_ and call them like that. We need to make it consistent with the other files. 
2. You have a loader imported but not exactly sure when its being used? I mocked what would happen to your page if the backend call took 5 seconds to respond, and this is what it looks like: 

https://user-images.githubusercontent.com/42155577/139790463-10c17147-dfd6-4a5f-9647-ca97b9dcd974.mp4



Any way you can add in the loader there? 
3. Once you reach like tablet/mobile view, your committee names/positions are like left-aligned. They should be center aligned. Fix it please. 
Screen Shot 2021-11-01 at 10 09 21 PM

**Comment by aaron-kirk** [comment]
This was part of the exec profile padding commit, but I also fixed the Loader thing. Forgot to put it in the title.

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Okay Aaron, it looks good. 

Small thing, that the client asked for. 

Can you move the little link icon for each of the members to the left of their position instead?
Screen Shot 2021-11-12 at 3 22 12 AM
 
Also update your branch.

**Comment by aaron-kirk** [comment]
image

**Review by Amrit-S — CHANGES_REQUESTED** [review]
So you're missing an edge case here. 

If the fetchExecCommittee has any error, it will return to you an empty array []. Your code assumes that will never happen, since you always get the name of the first element in the array back. But if it does, you'll crash the website by causing a segmentation fault.

In the case where it sends back an [], you probably just want to display to the user "No Executive Committees to show." instead of showing your Committee component. 
Screen Shot 2021-11-16 at 4 01 15 PM

**Review by amiteshksharma — CHANGES_REQUESTED** [review]
Aaron, couple things: 

image

Amrit said to center the text for mobile and it still isn't. what are you doing man

image

(For mobile only) Maybe increase the header text font size a little bit. A bit too similar to the text font, especially the "Executive Committee" font size

**Comment by aaron-kirk** [comment]
Leaving profile text left-aligned on mobile in accordance with Figma design

**Review by Amrit-S — CHANGES_REQUESTED** [review]
For your edge case message, make it the same font size and font family as the body text on the rest of your page. It's currently too big. And can you change it to say "No committees to show" instead. 

Screen Shot 2021-11-19 at 3 23 44 AM

**Review by Amrit-S — APPROVED** [review]
Good job :)

**Review by amiteshksharma — APPROVED** [review]
Lgtm

**Pull request merged**
