### PR TITLE
stepper component

### PR DESCRIPTION
**Pull request by amiteshksharma**
### Administrative Info
Monday Board ID: 1181608900
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Created stepper component

### Testing
How did you confirm your changes worked? 
- Tested it on the webpage

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| Video of use case |
| --- |
https://user-images.githubusercontent.com/51978213/139394641-09dce1aa-d38e-4718-bdb9-ce1f817bd3bd.mp4

| Stepper component image |
| --- |
image

### CODE REVIEW

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Okay Amitesh. Impeccable work. Clean code and you made a great component. I fixed a bit of your comments, and added a new prop to take care of special formatting for nodes - this will be needed for the EPubs page. 

Only thing I will say is that you need to change to color of the button once its been clicked to like an orange background. Your stepper should be taking care of that, not the caller. 

Other than that. Looks great!!!

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Better. You forgot that you need to do the same thing for "Add New" Button. If I click "Add New' right now, it will just keep the previous button still 'clicked' (i.e., have the clicked css on it). 

Also, update your PR.

**Review by thomas-gg — APPROVED** [review]
Looks great !

**Review by Amrit-S — APPROVED** [review]
Looks great!

**Pull request merged**
