### PR TITLE
Feature/patrick brown1/1293186139 create paypal component

### PR DESCRIPTION
**Pull request by PatrickBrown1**
### Administrative Info
Monday Board ID: 1181608900
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Implemented paypal smart buttons and hooked them up to backend routes for tracking memberships

### Testing
How did you confirm your changes worked? 
- PayPal sandbox accounts to make the payments
- Checked that the orders were added into the database after completion
- tested on invalid price/membership combinations

### Confirmation of Change 
image
image
image

### CODE REVIEW

**Review by Amrit-S — COMMENTED** [review]
Add in credentials for a PayPal testing account to our main Slack channel, and slo update your error alert to be a more general error message. See DM in slack for more details.

**Review by Amrit-S — COMMENTED** [review]
Think this looks fine. Waiting on Dhanush's approval first though.

**Review by dnanjunda — APPROVED** [review]
LGTM! Great job. Just make sure to merge main again.

**Review by Amrit-S — APPROVED** [review]
lgtm

**Pull request merged**
