### PR TITLE
Feature/patrick brown1/1254072311 website epub

### PR DESCRIPTION
**Pull request by PatrickBrown1**
### Administrative Info
Monday Board ID: 1181608900
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Implemented desktop and mobile views for epublication page
### Testing
How did you confirm your changes worked? 
- Went through various user flows with test const data

### Confirmation of Change 

https://user-images.githubusercontent.com/29768212/117588773-870bf900-b0da-11eb-967c-81559ce69b10.mov

https://user-images.githubusercontent.com/29768212/117588776-8b381680-b0da-11eb-8f0b-933da6ac94b7.mov

### CODE REVIEW

**Review by Amrit-S — CHANGES_REQUESTED** [review]
**_Amazing_** work Patrick! Seriously like good job. 

Few things:

1. You didn't do custom slides at all (neither for desktop nor for mobile). That is necessary for this PR so do them. 
2. Make the books open in a new tab, instead of the same tab. Make sure to use "ref=noreferrer" when you do this. 
3. So whenever I click on the "All" button, it automatically scrolls down to the bottom of the page (so I see the last books). Have that page be opened up at the top please so I see the first row of books instead. 
4. For Mobile version, have your heading titles for the section be much bigger. In general, your text in mobile should be a _bit_ bigger. 
5. So you did not use imports from "colorPalette.css" or "fonts.css" in constants folder at all in any of your css files. Have all your font/color references be from those two files only. Those are already imported into index.css so you shouldn't need to reimport them again. 
6. EPubSelectedSections.js is blank. Why is it in there? 
7. You have almost no commenting on any of your js files. Just add a few more comments. Its extremely sparse right now.

**Review by Amrit-S — COMMENTED** [review]
Looks good - will approve! Just waiting on @amiteshksharma review first. 

Though, @PatrickBrown1 , what commenting style is this?
Screen Shot 2021-05-13 at 3 31 07 AM

**Review by amiteshksharma — APPROVED** [review]
LGTM!

**Review by Amrit-S — APPROVED** [review]
Great job Patrick!

**Pull request merged**
