### PR TITLE
Newsletters routes and schema

### PR DESCRIPTION
**Pull request by dnanjunda**
### Administrative Info
Monday Board ID: 1181608900
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Created schema for Newsletters table
- Added routes for create, edit, and get entries for Newsletters table

### Testing
How did you confirm your changes worked? 
- Tested all routes with valid and invalid request body and params

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

To test, make requests for each route.

1. Add Newsletter: POST request to http://localhost:3000/newsletters/addNewsletter
Example body:
post_body

2. Get Entries: GET request to http://localhost:3000/newsletters/getAllNewsletters

3. Edit Newsletter: PUT request to http://localhost:3000/newsletters/editNewsletter/id (replace id with the entry you want to edit)
Example body(all fields are optional):
edit_body

### CODE REVIEW

**Review by thomas-gg — APPROVED** [review]
LGTM! May need to add default seed and also may need to delete the .eslintcache

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Hey Dhanush, good job!

Few things: 

1. Model Schema: Update your year to be UNSIGNED integer with 4 places. For your volume also make that be an UNSIGNED integer as well. 
2. For your editNewsletter route, if successful, just send back the newsletter object. 
3. Right now, your edit route is allowing everything to be editable, including createdAt, updatedAt, and id. You don't want a route to be able to edit these things. See Thomas's suggestion below on how to fix this.
4. You haven't added any seeds. Make sure to do this!

**Comment by thomas-gg** [comment]
Also you can use
```
body("createdAt").custom((val) => {
            return val !== undefined ? false : true;
}),
body("updatedAt").custom((val) => {
            return val !== undefined ? false : true;
}),
```
instead of installing lodash!

**Review by Amrit-S — APPROVED** [review]
Good job Dhanush!

**Pull request merged**
