### PR TITLE
Feature/dnanjunda/1254071746 joinus pages

### PR DESCRIPTION
**Pull request by dnanjunda**
### Administrative Info
Monday Board ID: 1181608900
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Implemented the join us page for desktop and mobile
- Paypal component and backend call hasn't been implemented yet
- Will add comments

### Testing
How did you confirm your changes worked? 
- Load the join us page on different screen sizes
- Tried filling out the form

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

Desktop:
JoinUs_Desktop
JoinUs_Desktop2

Mobile:
JoinUs_Mobile

### CODE REVIEW

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Nice job Dhanush!

Few things:

1. Spelling mistake - Student is spelled wrong. (Option #3)
Screen Shot 2021-05-30 at 3 58 19 PM

2. So I'm not sure if this is a bug, because I can't exactly test this without the PayPal component, but if someone chooses to enter some donation fee (let's say $5), and then unclicks the "I would like to donate in addition to membership fees" checkbox, are they still being tracked to donate $5, or is their donation amount nullified back down to $0? Whatever the case, the latter case should be happening, so if your current implementation is not doing that, please make that change. 
3. Near tablet screen. Your text gets very small -especially for the top part explaining what the checkbox means. And your fields have no spacing between them.
Screen Shot 2021-05-30 at 4 02 58 PM
Screen Shot 2021-05-30 at 4 03 54 PM

4. Mobile View: So your titles seem to be a bit too small, and spacing is a little bit all over the place. I would expect there to be more spacing between the different sections (i.e., between "Sign Me Up" and "Contact Information"). And maybe a tad bit less between each of the field s. 
5. Mobile View Part 2: So your field for if the member is returning or new, has overlap between the value and label type. I think you that TextField to have a lablel prop. Just remove it and instead just set it to have a placeholder value like you did with your other values. Also, your "list of organizations" field needs to be a bit more expanded since the text is being cut off. 
Screen Shot 2021-05-30 at 4 08 39 PM

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Nice job Dhanush!

Few things:

1. Can you center align the text for "Please fill out fields"? 
Screen Shot 2021-06-02 at 11 20 29 PM

2. For the text fields, on focus can you have the border color change to dark purple (from the css colorPalette) instead of black?
Screen Shot 2021-06-02 at 11 21 36 PM

3. There's no validation on the donation field. This should be numerical + decimals only. 
Screen Shot 2021-06-02 at 11 23 47 PM

**Review by PatrickBrown1 — APPROVED** [review]
Looks great! only issue I found was that the donation amount can be inputted as negative, but I'll approve
image

**Review by Amrit-S — APPROVED** [review]
LGTM

**Pull request merged**
