### PR TITLE
Feature/aaron-kirk/1254072054-navbar

### PR DESCRIPTION
**Pull request by aaron-kirk**
### Administrative Info
Monday Board ID: 1181608900
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Added Navbar stickied to top
- Created Navigation Panel, toggleable with a slide animation and a darkening overlay on page content
- Resources Navbar also stickied to top underneath normal Navbar
- Mobile breakpoint makes Navbar smaller and hides the Resources Navbar into a toggleable menu

### Testing
How did you confirm your changes worked? 
- Added some random Lorem Ipsum to the Home and Resources Landing pages to ensure Navbars were properly stickied
- Repeatedly opening and closing normal and resources navbar on mobile and desktop view
- Tested all the Chrome Devtools Mobile views

### Confirmation of Change 
https://youtu.be/u4QLWDf_i9E

### CODE REVIEW

**Review by amiteshksharma — CHANGES_REQUESTED** [review]
The navbar is very nice with the transition and the backdrop changes the opacity a little bit, which is very nice. However, a couple notes I want to make: 

1) I don't actually know how the sidebar should look like, I checked the figma and I have 0 idea. I will say, I feel it is very large in taking up the height of my screen. I feel like we could make it half the height or something. The text and blocks are very large. It could be possible since the main page is empty, it's hard to see how it would really look like, but it just feels really large for me. 

2) When changing the screen size, the navbar width and size stay constant (look at images below). I feel like the size of the sidebar should change as the screen size gets larger/smaller. 

image

image

I guess take this up with Amrit since I genuinely have no idea what the sidebar is supposed to look like on the page. The figma doesn't have the sidebar expanded on a page to see what it should look like, so I can't really give much more suggestions.

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Nice job Aaron! 

To  respond to some of @amiteshksharma points: 

1. So Aaron followed the Figma design to a T, so any concerns here would be a design issue. I pulled it up on my side, and I agree that it looks disproportionately big. The height is fine, but the text is honestly just too large. Its larger than the main logo on the NavBar which just makes it look awkward. I've slacked the designers about this, and I'll get back to you on this. But for now, I suggest making the navbar maybe 1/2 the width you have right now. Keep it the same height, but also make the text size significantly smaller. We'll see how that looks and go from there. 

2. Yeah I agree with this. Aaron, make you navbar proportional to the screen width. 

Also, your mobile view is great. However, I think you should center the component holding the pages and make the pages left-aligned. Right now it seems notably to the left. Also, maybe making the font-size a tad bit bigger for mobile.

**Review by amiteshksharma — APPROVED** [review]
LGTM! Font is much better and not half the size of my screen. Great work!

**Review by Amrit-S — APPROVED** [review]
Great **_great_** job Aaron!

**Pull request merged**
