### PR TITLE
Feature/navidboloorian/1254071651 epub backend

### PR DESCRIPTION
**Pull request by navidboloorian**
### Administrative Info
Monday Board ID: 1181608900
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Created schemas for EPubFilters, Publications, and FilteredPublications tables
- Created functions for interfacing with tables
- Created routes for tables

### Testing
How did you confirm your changes worked? 
-**EpubFilters**
- Created a seed to auto-fill table with values
- Checked that valid filter-checking exists by sending invalid routes
- **Publications**
- Tested with objects such as the following:
-  `{
    "title": "It",
    "author": "Steven King",
    "feature": true,
    "filters": [
        {
            "filterId": "english",
            "pdfLink": "https://pdfLink.pdf"
        },
        {
            "filterId": "french",
            "pdfLink": "https://newbook.pdf"
        }],
    "description": "this is descriptive ;)",
    "imageLink": "https://google.com"
}`
-Tested editing with each row individually, tested with/without filters
-**FilteredPublications**
-Tested dumping table when edit occurs

### Confirmation of Change 
-Access various routes as specified in routes/publications file

### CODE REVIEW

**Comment by navidboloorian** [comment]
I'm currently using an await in a foreach loop in the publications route because I couldn't find a workaround. Open to suggestions there.

**Review by thomas-gg — CHANGES_REQUESTED** [review]
Hey so I tested without any filters and that gives an error (which we want), without filterId (doesn't error) which I don't think we want, and without pdfLink (doesn't error). I am not sure if the valid filter value works because if I assign filterId to some garbage string I don't receive the 409 "Not a valid filter value" Instead of doing it in the route, you can have a custom validation using .custom and check to see if the if both the filterId and pdfLink are given in each filter, but I am not sure why the valid filter value didn't work on my end

**Comment by navidboloorian** [comment]
I have an await in a for loop but I can't figure out a work around

**Review by thomas-gg — APPROVED** [review]
LGTM! I don't have any recommendations for the loop in addPublication

**Review by Amrit-S — APPROVED** [review]
Alright, a lot of changes were made. I simplified the tables a bit, and took out some of the verification code since the table constraints take care of it (i.e., checking if the filterId is valid). Also 'optomized' code so there isn't as many awaits in loops - used Promises.all/Promises.allSettled to add some parallelism to calls.

Hopefully its good. Had Thomas test it a bit too.

**Pull request merged**
