### PR TITLE
Feature/amrit s/1319539439 resources landing page

### PR DESCRIPTION
**Pull request by Amrit-S**
### Administrative Info
Monday Board ID: 1181608900
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Added Resources Landing page (desktop + mobile responsive)
- Fixed some css for HeaderResources component

### Testing
How did you confirm your changes worked? 
- Tested on different browser sizes

**Note: There is a bug with the height of the div in Safari/IE, with there being some extra space left. This bug is coming from ResourcesHeader.js, which will be fixed at a later time.** 

### Confirmation of Change 

Screen Shot 2021-05-24 at 2 49 50 AM
Screen Shot 2021-05-24 at 2 49 59 AM

### CODE REVIEW

**Review by PatrickBrown1 — CHANGES_REQUESTED** [review]
Looks good, I'm just worried about the page being scrollable when there isn't anything lower on the page. The height on the header should probably be reduced to 100vh - navbar height

**Review by PatrickBrown1 — APPROVED** [review]
Fixed requested changes. Looks good now

**Review by dnanjunda — CHANGES_REQUESTED** [review]
Looks good Amrit! Just a small issue I found is that at a certain screen width, there's some white space below the header. I'm not sure if this needs to be fixed. Also, make sure to take care of the merge conflicts.

Resources_Landing

**Review by dnanjunda — COMMENTED** [review]
The whitespace issue is fixed, but the page is now scrollable again like Patrick said above. If that's not an issue, let me know and I'll approve.

**Review by amiteshksharma — APPROVED** [review]
LGTM, great work!

**Review by dnanjunda — APPROVED** [review]
LGTM!

**Pull request merged**
