### PR TITLE
Volunteer Page

### PR DESCRIPTION
**Pull request by dnanjunda**
### Administrative Info
Monday Board ID: 1181608900
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Implemented the volunteer page for desktop and mobile (may have minor bugs on mobile)
- Still need to link to backend to store volunteer form data
- Will add comments

### Testing
How did you confirm your changes worked? 
- Load volunteer page on different screen sizes

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

Desktop:
Volunteer1
Volunteer2

Mobile:
Mobile_Volunteer

### CODE REVIEW

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Hey Dhanush! Looks very nice!

Few things: 

1. Your layout in general really crashes near iPad mode. The committee options all bleed within one another and there is no spacing between the contact information fields at the top. 
Screen Shot 2021-05-30 at 3 25 55 PM
Screen Shot 2021-05-30 at 3 26 04 PM
Screen Shot 2021-05-30 at 3 26 22 PM

2. For the little red asterisks, can you make them just a tad bit bigger? Maybe increase their font-size by 2 -3 pixels.


3. I think in general, you need to retest your css for mobile. Skimming through the mobile screens, a lot of the layout crashes, especially for horizontal mobile.
Screen Shot 2021-05-30 at 3 29 39 PM
Screen Shot 2021-05-30 at 3 29 45 PM

4. For form validation, there needs to be some consistency between all the pages - Join Us, Volunteer, and Contact. For Contact, if any required fields were missing/contained bad information, I simply changed that particular TextField's border color to red and displayed a snack box for 6 seconds stating "Required fields are missing.", or whatever appropriate error message you think should be shown. Please do something similar. Take a look at the Contact page PR (or let me know via DM), on how to do this with state fields. 

5. Make sure to repull from master. Your branch seems to a few pulls behind.

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Hey Dhaush! It looks much better!

Just a few quick things:

1. Mobile View: Can you increase the font size of your headers on the page (i.e., Sign Me Up, Contact Information) and also increase the subtext on the interest options? Its really small and hard to read right now. 
2. Move your "* indicates a required field" to the top of the page, right before "Sign Me Up". I think it would make more sense there, and not at the end of the form since the form is quite long and people might see it too late. 
3. Your "Select Country" field gets rectangular for mobile/tablet, while the other fields are rounded? Can you make it rounded as well?
Screen Shot 2021-06-02 at 1 16 29 AM

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Nice job Dhanush!

Quick things: 

1. Increase spacing between interests for Galaxy Fold:
Screen Shot 2021-06-02 at 11 36 08 PM
2. On field focus, make border color dark purple to keep consistency with the other forms.



3. Slightly reducing the amount of white space between the required field disclaimer and the bottom of the image by a little when hitting mobile/tablet view. It looks a bit uneven right now. 
  Screen Shot 2021-06-02 at 11 38 45 PM

**Review by PatrickBrown1 — APPROVED** [review]
Looks good! My only concern is being able to put an invalid email address (which I'm sure is handled by the backend) and getting no frontend error in response. You could use this regex "^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+$" if we wanted to implement it.

**Review by Amrit-S — APPROVED** [review]
Alright Dhanush I'm approving this.

But for future reference, you're spacing on mobile is a bit inconsistent:
Screen Shot 2021-06-03 at 1 58 06 PM

**Pull request merged**
