### PR TITLE
Button Component (Admin Tool)

### PR DESCRIPTION
**Pull request by Amrit-S**
### Administrative Info
Monday Board ID: 1181608900
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Created a customizable button component for the admin tool (updates css and onClickCallbacks)

### Testing
How did you confirm your changes worked? 
- Played around with different parameters passed to button (seems to hold) 
- Can see the example usage on the News & Events Slider page

### Confirmation of Change 
Screen Shot 2021-10-13 at 1 53 59 AM

### CODE REVIEW

**Review by ASharma2001 — APPROVED** [review]
lgtm

**Review by amiteshksharma — APPROVED** [review]
approved on wrong account again.

**Review by aaron-kirk — CHANGES_REQUESTED** [review]
Overall fine, but I really don't like the little bit of drop shadow 😢😢
image

**Review by aaron-kirk — APPROVED** [review]
Looking beautiful 😻 😻 😻

**Pull request merged**
