### PR TITLE
Feature/patrick brown1/1293188982 newsletters page

### PR DESCRIPTION
**Pull request by PatrickBrown1**
### Administrative Info
Monday Board ID: 1181608900
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Implemented mobile and desktop versions of the newsletters page, including creating newsletter cards and a grid to render them

### Testing
How did you confirm your changes worked? 
- I created 50 newsletters of dummy data to test the pagination, as well as changed around the viewport size to responsive desktop and mobile sizes.

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.
image
image
image

### CODE REVIEW

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Great job Patrick! See more commenting as well :)

Your layout crashes at mobile for Galaxy Fold screen:

Screen Shot 2021-05-24 at 3 22 11 PM

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Better Patrick - Galaxy looks cleaner. 

Just a few style edits really for mobile: 

1. Decreasing padding on mobile by a little bit, especially the vertical distance between two newsletters. 
2. Increase font size a bit overall, especially for the headers. They barely look bigger than the newsletter text. 
Screen Shot 2021-05-25 at 2 27 24 PM

**Review by Amrit-S — COMMENTED** [review]
Looks great Patrick! Amazing job as always :)

**Review by aaron-kirk — CHANGES_REQUESTED** [review]
Super clean!

A small change though, the pagination overflows on the Galaxy Fold view (this happens specifically when you are in the double digit page range and ALSO not at the very end so that ellipses are rendered on both sides)
image

Also I know Amrit said to decrease the vertical padding on mobile, but I honestly feel like it could be increased a bit—on mobile and desktop view. I can imagine how, if one's whole screen is filled with rows of newsletters, one could get confused whether the title is referring to the image above or below.

**Review by aaron-kirk — APPROVED** [review]
looks good! :D

**Review by Amrit-S — APPROVED** [review]
Fantastic job Patrick!!

**Pull request merged**
