### PR TITLE
Feature/amiteshksharma/1898555629 conferences population

### PR DESCRIPTION
**Pull request by amiteshksharma**
### Administrative Info
Monday Board ID: 1181608900
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Added all the conferences from the original website into the models/conference folder
- Added a way to handle if there is a query param passed in for the conferences page

### Testing
How did you confirm your changes worked? 
- Manual testing

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

Just run the server and then run the client/website and the information should be populated. 

Video of testing the **&confNum=[number]** param

https://user-images.githubusercontent.com/51978213/142054599-ff1f6044-73cd-4c3e-9fec-279f366b19b9.mp4

### CODE REVIEW

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Nice nice job Amitesh :)

Few things: 
1.  New layout that we discussed over slack: stepper absoluately positioned on left, and the right having the slide show wrapped around the text in Overview 

2. I think on the admin tool, we're going to have to make the Theme field a text - editor. Otherwise, everything looks clumped as hell on the page and hard to read. Just reuse the one you made. And update it so that it takes a prop on whether or not images is an enabled option. For this one, do not enable images. In terms of population, can you add the theme as a nicely formatted Html string with relevant hyperlinks/spacing  so it looks nice. 

3. Can you increase spacing between stepper and the the right side by like idk 5 pixels

Screen Shot 2021-11-16 at 5 03 35 PM

4. On the stepper, just put the "city, country" , not like all the information. Otherwise its too crowded. Use string parsing to do this

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Screen Shot 2021-11-23 at 10 59 54 PM
This was the only weird thing I caught. Not sure why you have 'no problems available' listed, but yet you state one program. 


Also, update your branch with main.

**Review by aaron-kirk — CHANGES_REQUESTED** [review]
I wasn't able to reproduce Amrit's issue, but the way the images stretch and shrink when you change tabs makes me very sad :(
Also fine if you don't wanna fix it though, so lmk

https://user-images.githubusercontent.com/36803028/143196489-73ad5a95-89e4-45a1-8457-cc03b2f1929a.mp4

.

**Review by aaron-kirk — APPROVED** [review]
the image thingy is not a big deal. otherwise, LPTM

**Review by Amrit-S — APPROVED** [review]
Less shitty than expected. Congrats - i'll take it

**Pull request merged**
