### PR TITLE
Feature/amiteshksharma/1293189547 buddhist culture

### PR DESCRIPTION
**Pull request by amiteshksharma**
### Administrative Info
Monday Board ID: 1181608900
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- I implemented the Buddhist Culture page and it takes in props for it's data

### Testing
How did you confirm your changes worked? 
- I tested it on different screen widths

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| Video of testing |
|  https://user-images.githubusercontent.com/51978213/119939182-4b7a8700-bf42-11eb-97b0-d07f362b4230.mp4 |

### CODE REVIEW

**Review by aaron-kirk — APPROVED** [review]
Looks all good to me! Only thing is I personally feel like the extra divider at the end is weird, but it's in the design and it's not really a big deal either way.

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Amazing job Amitesh! Absolutely beautiful 

Just 2 points of correction here: 

1. Can you make the header font-size a bit bigger in your subsection for mobile. Like maybe increase it by 4-5 pixels.
2. For iPad and iPad Pro the screen has a lot of additional white space to it at the bottom:
Screen Shot 2021-05-28 at 1 35 38 AM

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Okay, so yours is having the same issue as Aaron where the scroll thing literally crashes into the footer if you scroll down enough. Try making the scroll thing sticky (scrolls with you), only until it reaches the end of the last paragraph. Once it reaches the end, just have it remain static on the page (i.e., stops scrolling with you).

Screen Shot 2021-05-29 at 3 09 15 PM

**Review by Amrit-S — APPROVED** [review]
Gorgeous!

**Pull request merged**
