### PR TITLE
finalizing the text editor component for admin tool

### PR DESCRIPTION
**Pull request by amiteshksharma**
### Administrative Info
Monday Board ID: 1181608900
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Added a text editor to be reusable
- Generates stringified HTML 

### Testing
How did you confirm your changes worked? 
- Rendered the string on the screen while typing in the test editor

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| Text editor with picture upload |
| --- |
Screen Shot 2021-10-19 at 2 04 36 PM

### CODE REVIEW

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Amazing like always!

Just like a small thing. 

1. So by default, 'font' is set to 'font' but when I'm typing something it's clearly using a specific version?  Not sure if you can fix this/its an internal bug, but I think it should have a default font chosen. 

2. Can you add in an option for 'text-color' please? I think it might be useful to include that. If it's not available with the editor, then no need.

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Honestly its good to go. Added in a few tweaks myself. 

Just try to add in a black border around the editor if you can. If for whatever reason it takes more than 4 minutes to figure out, just skip it. I'll approve. 
Screen Shot 2021-10-21 at 10 13 36 PM

**Review by Amrit-S — APPROVED** [review]
Great job!

**Review by thomas-gg — APPROVED** [review]
Looks awesome! :D

**Pull request merged**
