### PR TITLE
Feature/patrick brown1/1318938129 admin tool navbar

### PR DESCRIPTION
**Pull request by PatrickBrown1**
### Administrative Info
Monday Board ID: 1181608900
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Created navbar for the admin page

### Testing
How did you confirm your changes worked? 
- Clicked through each link on the nav bar

### Confirmation of Change 

image
image
image

### CODE REVIEW

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Nice job Patrick - as usual!

My only thing for this would be that once a page is clicked, you have the purple navbar have the darkened effect on that corresponding tab, but not the orange navbar. 

So if I click on Home -> Introduction, once I click on Home again I would want to have Introduction be darkened to indicate that was the current page I was on.

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Looks great Patrick! Just make sure to pull from master. 

Waiting on the approval of the other reviewer first.

**Review by aaron-kirk — APPROVED** [review]
looks great!

**Review by Amrit-S — APPROVED** [review]
LGTM!

**Pull request merged**
