### PR TITLE
Feature/navidboloorian/1867106890 sync epubs to backend

### PR DESCRIPTION
**Pull request by navidboloorian**
### Administrative Info
Monday Board ID: 1181608900
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Synced frontend and backend for Epub page
- Changed name of e-pub pages
- Made redirects optional

### Testing
How did you confirm your changes worked? 
- Spam refreshing
- Inputted temporary data into database

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| [TODO Screenshot Title] |
Epubs page
| [TODO Screenshot Link] |
image

### CODE REVIEW

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Nice job Navid. I'll take a closer look at code changes in like later today, but looking at the website visually - nice job. 

One thing I noticed:

Once you click on the "All" button for a section, it slides down to the page bottom. It's kind of annoying. Can you have it scroll up to the top of the page to avoid this? 

https://user-images.githubusercontent.com/42155577/141477938-705fff40-dc84-4c0f-8b36-ad5442b80a42.mp4

**Review by amiteshksharma — CHANGES_REQUESTED** [review]
Hey Navid, glad to have you back. I agree with Amrit's point above. It seems to only be an issue with the second and third sections and not the first. I have one comment though

The title and author name have a space between them for some of them. I'm not a big fan as it looks weird for some of them. Maybe we can have it next to each other regardless of how long the title is? Like using the image below, I think if we have the title "It" right above "Stefan King" rather than that gap, it would look better. I'll leave this one up to you though, just a personal thought.

image

Besides that, it looks good.

**Review by amiteshksharma — CHANGES_REQUESTED** [review]
Navid, I hate to do this but the scrolling issue seems to still somewhat be there. I can't lie if you don't want to/can't fix this anymore lmk on Slack because besides this it looks good. 

https://user-images.githubusercontent.com/51978213/142585051-390993ef-58cf-46aa-8cba-9cc30c510559.mp4

.

**Review by Amrit-S — APPROVED** [review]
Looks fabulous. Great job!

**Review by aaron-kirk — APPROVED** [review]
truly phenomenal work.

**Review by amiteshksharma — APPROVED** [review]
LGTM

**Pull request merged**
