### PR TITLE
Feature/amiteshksharma/1254072176 conference page

### PR DESCRIPTION
**Pull request by amiteshksharma**
### Administrative Info
Monday Board ID: 1181608900
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Completed the conferences page
- Built a reusable component for the vertical stepper 
- built a reusable component for the modal
- The page can switch between the 'theme' tab and the 'overview' tab 
- The files are downloadable when clicked
- The stepper renders 9 items at a time and supports pagination

### Testing
How did you confirm your changes worked? 
- I changed the viewport width to determine how it would look, and it looked good as of right now. I didn't have time to record so apologize for that. However, I expect there to be some CSS issues with some components here and there.
-  One decision I made was to have it overflow as I don't know what the current design should be for the smaller screens. All this means is when it reaches <1500px, the div the information is inside is scrollable, so you can scroll left to right to see the information. This might need to change. 

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| image |

### CODE REVIEW

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Good job Amitesh - it looks very nice:) !

Few things: 

1. Your "Theme" and "Overview" buttons are like insanely small compared to the designs. They need to bigger. Your sign-up button should also be bigger (same size as your "Theme" and "Overview"), and definitely more rounded. Its like less rounded for some reason and I'm not sure why. 
2. You have an awkward amount of whitespace on the lefthand side of the screen. The amount of whitespace should be the same on the left and right, and overall should be reduced. 
3. The amount of whitespace between the stepper and the text versus the text and slideshow is like uneven. Make it even. Also, everything seems congested together in the middle of the page, when there should be spacing. Make use of your padding and margins. 
4. So on the "Overview" section, your orange headers are too small. They should expand to the width of the div, and they clearly are stopping early. Should be more like this: 
Screen Shot 2021-05-10 at 10 26 12 PM
5. Color of the text inside of your stepper should be purple, not black. Also, location text on the stepper should not be bolded at all (not even on click). 


6. Your page is not desktop responsive. If I try to reduce the screen size, the video and slideshow basically go to hell. If you don't know what to do for these smaller desktop screens, I suggest you change the direction of your layout so the righthand side stacks. So keep stepper on your left, and then on the righthand side have the text stack on top of the slideshow/video (so its like a vertical stacking instead of horizontal stacking). 
7. Keep your Slideshow components inside of` /components/conferences`, not `/components/Main/conferences`. 
8. Bruh, where are you comments on your javascript files? Have headers on everything, and at least a few non-redundant body comments.

**Review by aaron-kirk — CHANGES_REQUESTED** [review]
I personally think it looks good and matches the design well.

- Make sure the Sign-up button should have border-radius 50%.
- I'm not sure how this will play with the carousel component, but the right-hand side of the page definitely needs to have some max-width set.
- The margins on the left could be reduced. Maybe you could reduce the size of the stepper circles.
- The orange buttons seem like they have a slight box-shadow in the figma.
- I think the stepper is really dope, super clean, but perhaps the circles could be made a bit smaller.
- Make sure you also implement the mobile design from the figma. (https://www.figma.com/file/sDAGoIDRbIqYyJbbW6OzTZ/SI-Website-Revamp?node-id=452%3A2420)
- Text on the stepper itself and the little page changer should be purple

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Nice job Amitesh!

Few things: 

1. So for this small desktop screen, you don't want your slideshow/video to be that far down. It should be ideally staying within its own space on the right hand side of the screen, and not bleeding underneath the stepper. If you feel like the space is too small for a video/slideshow at this screen size, then just trigger your mobile view a bit early so it looks good. Mobile view just has to set in by 750px, but you can make it collapse earlier if it makes the screen look better. Which looking at this, I would recommend you to do.

Screen Shot 2021-05-20 at 1 11 26 AM

2. For mobile slideshow, make your header/title text bigger. Its too small for a heading right now. And the opacity for that purple div is too low. Bump it to like maybe 85% or something for its RGBA. 
Screen Shot 2021-05-20 at 1 15 14 AM

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Okay, Amitesh. Better, but a few of your mobile screens need a few tweaks. 

1. Galaxy Fold: Your vertical stepper is literally being cut out, and your slideshow purple div is extremely stretched. I highly recommend just adding some custom css for 300 and below to capture those screens. 
Screen Shot 2021-05-22 at 1 08 10 AM

2. Your iPad screens are looking lopsided. Since you're stacking everything on the right, the amount of white space you have from the top on the righthand side just looks distracting. Honestly, my first recommendation for this screen is to have your mobile view just switch early, so it renders for the tablet/ipad view as well. So, like trigger mobile layout perhaps <= 800 pixels occurs. That should make tablet look cleaner. 
Screen Shot 2021-05-22 at 1 07 39 AM
Screen Shot 2021-05-22 at 1 07 51 AM

**Review by Amrit-S — COMMENTED** [review]
Amazing job! Looks great! Just waiting on Aaron's approval now.

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Oh wait :( There's a few lint errors on your PR. Fix those first 

Screen Shot 2021-05-24 at 12 42 08 AM

**Review by aaron-kirk — APPROVED** [review]
Sorry for the long wait—everything looks great on all views. Very clean!

**Review by Amrit-S — APPROVED** [review]
LGTM :) Nice work!

**Pull request merged**
