### PR TITLE
Feature/patrick brown1/1254072643 create slideshow component

### PR DESCRIPTION
**Pull request by PatrickBrown1**
### Administrative Info
Monday Board ID: 1181608900
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Created custom slideshow component

### Testing
How did you confirm your changes worked? 
- Tested with images I inserted. Should work for any div.

### Confirmation of Change 
https://user-images.githubusercontent.com/29768212/116647453-6ea81b80-a92f-11eb-8147-c220287e0738.mov

### CODE REVIEW

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Great work - especially finishing it the same day! Few nit picky things:

1. Don't have your component be under components/main, just have it be under components/. 
2. Add a file header (it can be 1 - 2 lines) to your components file, stating functionality and component requirements for props. 
3. Your comments exist, but I think one literally cuts off in the middle of a thought. Fix it :)

**Review by Amrit-S — COMMENTED** [review]
Looks good to me. Waiting on Amitesh's approval first.

**Review by thomas-gg — APPROVED** [review]
I really love the alt tag for the images right now. On a wider window, the images are stretched pretty weird, but i don't have a suggestion on how to fix that. So for now we have long pandas!

**Review by Amrit-S — COMMENTED** [review]
@thomas-gg So for the images, Patrick right now has some dummy slides that he added that have full on images for content. Expectation is that since EPubs, Conferences, and Home page will reuse this slideshow component but with their own custom "slides", they would be responsible for making sure the images do not look weird in their slide components. The slideshow is simply a container for the slides, and is not responsible for the physical content of the slides.

**Review by Amrit-S — APPROVED** [review]
Great job Patrick! 

Note: Image stretching will be resolved through custom slide components, utilizing mainly the `object-fit: cover` css (thanks to @aaron-kirk 's suggestion).

**Pull request merged**
