### PR TITLE
Feature/amiteshksharma/1737703859 backend conferences connection

### PR DESCRIPTION
**Pull request by amiteshksharma**
### Administrative Info
Monday Board ID: 1181608900
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Integrated the backend with the website
- Added a "We have no conferences to show you at this time" if there is no conferences or if the backend has some error

### Testing
How did you confirm your changes worked? 
- Tested in the browser

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

N/A

| [TODO Screenshot Title] |
| --- |
| [TODO Screenshot Link] |

### CODE REVIEW

**Comment by amiteshksharma** [comment]
Current page with backend 
image

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Nice job Amitesh.

Few things:

1. Your scroll container is not big enough, and scrolling should not be enabled on all the text. For the 'theme' section, only the description text (i.e., everything below the sign up button) should have be wrapped around a scroll container. Not the whole left hand side of text like you have now. Also, make sure that scroll container matches the bottom of the video on the right hand side. 
Screen Shot 2021-10-10 at 1 16 35 AM



2. Same thing as above, but this time for the 'overview' section. Everything programs and below should be wrapped around a scroll div. That's it. Also make sure to make the container hit the bottom of the video.

Screen Shot 2021-10-10 at 1 13 08 AM


3. You need to account for the case if no video link is passed, like at all (NULL). This will be the case for the earlier conferences, so you need to update your visual layout so it still looks good. Right now, it's just a bunch of white space on the right. 

If not video link is passed, just make everything Programs & below stretch out to the width full width. So it takes up some of the white space. 
Screen Shot 2021-10-10 at 1 20 36 AM

**Review by Amrit-S — CHANGES_REQUESTED** [review]
Great job Amitesh. Looks much better. 

So few things:

1. I noticed that once you change to like mobile format some things crash. Your theme content text like is bleeding into the 
left side of the screen. And in the case you have no video available, there's this big empty empty white space. 

Screen Shot 2021-10-12 at 11 32 27 PM
Screen Shot 2021-10-12 at 11 31 41 PM


2. You should only show the sign up button if the value is non-null. I think you are showing the button regardless of whether the value passed back to you is null.

**Review by Amrit-S — APPROVED** [review]
lgtm

**Review by aaron-kirk — APPROVED** [review]
Looking good -- no complaints

**Pull request merged**
